application: alltheseboxes
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /images
  static_dir: images

- url: /src
  static_dir: src
  
- url: /cache.manifest
  static_files: cache.manifest
  upload: cache.manifest
  mime_type: text/cache-manifest
  expiration: 1s
  
- url: /robot.txt
  static_files: robot.txt
  upload: robot.txt

- url: /.*
  script: main.py
