application: alltheseboxes
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /src
  static_dir: src

- url: /.*
  script: main.py
