application: alltheseboxes
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /src
  static_dir: src
  
- url: /cache.manifest
  static_files: cache.manifest
  upload: cache.manifest
  mime_type: text/cache-manifest

- url: /.*
  script: main.py
